#!/usr/bin/env python3
"""Check regression cases output and print a concise report.

Designed for option (2): allow missing-from-truth alerts.

Input: regression_cases.csv generated by build_regression_cases.py
Output: stdout + optional --report text file

Rules:
- Always report counts: total, anchored, missing-from-truth, expected-owned alerts.
- If --fail-on-anchored-drop is set, exit non-zero when anchored < threshold.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cases", required=True, help="regression_cases CSV")
    ap.add_argument("--report", default="", help="optional path to write a text report")
    ap.add_argument("--fail-on-anchored-drop", type=int, default=-1, help="if >=0, fail when anchored < this")
    args = ap.parse_args()

    df = pd.read_csv(args.cases, dtype=str, low_memory=False).fillna("")

    total = len(df)
    anchored = int((df.get("anchor_method", "") == "TITLE_NORM_EXACT").sum())
    missing = int((df.get("anchor_method", "") != "TITLE_NORM_EXACT").sum())
    expected_owned = int(pd.to_numeric(df.get("alert_expected_owned", 0), errors="coerce").fillna(0).astype(int).sum())

    # highest-signal list: expected-owned AND missing-from-truth
    alert_df = df[(df.get("alert_expected_owned", "0").astype(str) == "1") & (df.get("anchor_method", "") != "TITLE_NORM_EXACT")]

    lines = []
    lines.append("Regression check")
    lines.append(f"- cases_total: {total}")
    lines.append(f"- anchored_to_truth_title_norm: {anchored}")
    lines.append(f"- missing_from_truth_title_norm: {missing}")
    lines.append(f"- expected_owned_alerts: {expected_owned}")
    lines.append("")
    lines.append("Top missing-from-truth (expected-owned) examples:")
    for _, r in alert_df.head(20).iterrows():
        lines.append(
            f"- {r.get('work_title','')[:80]} | interpreter={r.get('interpreter','')[:50]} | publisher={r.get('publisher','')[:50]}"
        )

    report = "\n".join(lines) + "\n"
    print(report)

    if args.report:
        p = Path(args.report)
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(report, encoding="utf-8")

    if args.fail_on_anchored_drop >= 0 and anchored < args.fail_on_anchored_drop:
        raise SystemExit(2)


if __name__ == "__main__":
    main()
