#!/usr/bin/env python3
"""Normalize parsed OBRAS/FONOGRAMAS CSV exports into a stable schema.

Inputs: runs/reference/obras_parsed.csv, fonogramas_parsed.csv (generated by parse_estelita_reports.py)
Outputs: runs/reference/obras_truth.csv, fonogramas_truth.csv + summary JSON

Key fixes:
- Drop repeated in-body header rows (e.g., rows where TITULAR: == 'CÓD. OBRA')
- Rename columns into stable field names
- Basic cleanup of codes (strip, normalize NaNs)
"""

import argparse
from pathlib import Path
import json
import pandas as pd


def norm_str(x):
    if pd.isna(x):
        return None
    s = str(x).strip()
    if s == '' or s.lower() in {'nan','none','null'}:
        return None
    return s


def normalize_obras(df: pd.DataFrame) -> pd.DataFrame:
    # Drop repeated header rows
    marker = df.get('TITULAR:')
    if marker is not None:
        df = df[~marker.astype(str).str.contains('CÓD\. OBRA', case=False, na=False)].copy()

    out = pd.DataFrame({
        'work_code': df.get('TITULAR:'),
        'iswc_or_author_code': df.get('12592979'),
        'title': df.get('col4'),
        'work_type': df.get('col10'),
        'editor_flag_or_date': df.get('EDITOR'),
        'raw_pseudonimo': df.get('ESTELITA'),
        'raw_category': df.get('CATEGORIA:'),
    })

    for c in out.columns:
        out[c] = out[c].map(norm_str)

    return out


def normalize_fonogramas(df: pd.DataFrame) -> pd.DataFrame:
    marker = df.get('TITULAR:')
    if marker is not None:
        df = df[~marker.astype(str).str.contains('CÓD\. ECAD', case=False, na=False)].copy()

    out = pd.DataFrame({
        'ecad_code': df.get('TITULAR:'),
        'isrc': df.get('12592979'),
        'situacao': df.get('EDUARDO MELO PEREIRA LTDA'),
        'title': df.get('col5'),
        'rotulo': df.get('col10'),
        'associacao': df.get('col12'),
        'participacao': df.get('col13'),
    })

    for c in out.columns:
        out[c] = out[c].map(norm_str)

    return out


def summarize(df: pd.DataFrame, title_col='title'):
    s = {}
    s['rows'] = int(len(df))
    s['cols'] = int(df.shape[1])
    if title_col in df.columns:
        tt = df[title_col].dropna().astype(str)
        s['title_nonnull_pct'] = float((df[title_col].notna()).mean())
        s['unique_titles'] = int(tt.nunique())
        s['sample_titles'] = tt.head(10).tolist()
    return s


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--obras-in', required=True)
    ap.add_argument('--fonogramas-in', required=True)
    ap.add_argument('--out-dir', required=True)
    args = ap.parse_args()

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    obras_raw = pd.read_csv(args.obras_in)
    fono_raw = pd.read_csv(args.fonogramas_in)

    obras = normalize_obras(obras_raw)
    fono = normalize_fonogramas(fono_raw)

    obras_out = out_dir / 'obras_truth.csv'
    fono_out = out_dir / 'fonogramas_truth.csv'
    obras.to_csv(obras_out, index=False)
    fono.to_csv(fono_out, index=False)

    summary = {
        'obras': summarize(obras),
        'fonogramas': summarize(fono),
    }
    (out_dir / '_summary.json').write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding='utf-8')

    print(json.dumps(summary, ensure_ascii=False, indent=2))


if __name__ == '__main__':
    main()
